### ISSUE TITLE
DevOps (AWS & Stack Choices)

### ISSUE THREAD

**Issue by millzpaugh** [mapbox/resistbotmap#1]
Initially, we setup the node app with a MongoDB backend. After talking with @jakepruitt, it became apparent that there are better ways to structure the project that reflect Mapbox's suite of AWS tools & processes. These suggestions were broken to several steps: 

**Phase One**
1) Replace MongoDB with DynamoDB. 
2) Generate a GeoJSON file with Rapid Pro user data and geospatial info based on state & congressional district. 
3) Use a `mb-pages` branch to create a frontend that interacts with the geoJSON file. 

**Phase Two**
- Swap geojson file out with a direct connection to dynamoDB to quick query capabilities and access to more data. 
- Use the Mapbox datasets API as a geojson store. 
- If we want to incorporate address verification later in the project, use a Lambda function to hit the LOB endpoint and verify an address. 

cc @gretacb

**Comment by GretaCB** [comment]
# Currently moving

Feel free to edit as we go.

## Overall Layout
Per chat with @millzpaugh , we're thinking the overall layout will be:

### Two Repos
1. `put-it`: 🌀 ➡️  Get user data, aggregate and transform into final geojson, then PUT final data to datastore. This shall be the data processing piece.
2. `get-it`: ➡️ 🗺  Get final data from datastore and slap it on a map. This shall be the front end piece.

### Datastore
Per chat with Jake
> operating on mongodb locally for now is fine to generate static sources, it would make iterating on data a little bit faster, and you might want to iterate a little while before you decide if you even want to use a large data store

First phase: 
- `mongodb` to hold user data dump
- `s3` to hold final geojson datasources

Second phase (if we deem it necessary):
- `dynamodb` to hold user data dump
- `dynamodb` to _also_ hold geojson features/datasource?

## Devops/Infrastructure
Going to lean on already-existing mapbox AWS infrastructure and sample projects to prop up the app and database (see above)
- [ ] When we're ready for the next db iteration: [Replace MongoDB with DynamoDB](https://github.com/mapbox/resistbotmap/issues/4)

## Data wrangling
**Static data per Phase 1**
- [ ] [Add congressional districts to reps data](https://github.com/mapbox/resistbotmap/issues/3)
- [ ] [Merge US state geospatial data & state level user data](https://github.com/mapbox/resistbotmap/issues/4)
- [ ] Put static data fixtures to s3 and add s3 access to the app

## The map
- [ ] [Map object](https://github.com/mapbox/resistbotmap/pull/2), including https://github.com/mapbox/resistbotmap/issues/4
